config/routes.rb
Rails.application.routes.draw do
mount Attachinary::Engine => "/attachinary"
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }

  resources :talents, only: [:create, :new, :update, :edit, :index, :show]
  resource :profile, only: :show


  resources :conversations do
    resources :messages
  end

  resources :conversations, only: [:show] do
    resources :appointments, only: :create
  end

  root to: 'pages#home'
end

app/models/talent.rb
class Talent < ApplicationRecord
  include PgSearch

  pg_search_scope :global_search,
    against: [:description, :talent_proposed],
    associated_against: {
      user: [ :first_name, :last_name, :address, :email ],
      category: [ :name ]
    }

  belongs_to :category
  belongs_to :user

  validates :talent_proposed, presence: true
  validates :description, presence: true
end

app/controllers/talents_controller.rb
class TalentsController < ApplicationController
  def new
    @talent = Talent.new
  end

  def create
    @talent = Talent.new(talent_params)
    @talent.user = current_user

    if @talent.save
      redirect_to profile_path
    else
      render 'new'
    end
  end

  def show
    @talent = Talent.find(params[:id])
    @recipient = @talent.user
    @category = Category.new
  end

  def edit
    @talent = current_user.talents.find(params[:id])
  end

  def update
    @talent = current_user.talents.find(params[:id])
    if @talent.update(talent_params)
      redirect_to talent_path
    else
      render 'edit'
    end
  end

  def index
    @talents = Talent.where.not(user: current_user)
    @category = Category.find(params[:category_id]) if params[:category_id].present?
    @query = params[:query]
    @categories = Category.all

    if params[:category_id].present?
      category = Category.find(params[:category_id])
      @talents = @talents.where(category: category)
    end

    if params[:query].present?
#      @talents = @talents.where("talent_proposed ilike ?", "%#{params[:query]}%")
      @talents = @talents.global_search params[:query]
    end
  end

  private

  def talent_params
    params.require(:talent).permit(:category_id, :talent_proposed, :description, :lesson)
  end
end

app/views/talents/_form.html.erb
<div class="container">
  <div class="row center">
    <h3 class="post center">Share your talent</h3>
    <div class="new_talent">
      <div class="col-md-6 col-md-offset-3">
      <BR>
        <%= simple_form_for(@talent) do |f| %>
        <%= f.association :category, label: 'Select the category matching with your passion', class: 'section' %>
        <%= f.input :talent_proposed, label:'What\'s your talent?', placeholder: 'Piano' %>
        <%= f.input :description, label: 'Introduce yourself and describe your passion to the community', placeholder: 'Hello, I have been playing piano for 15 years and would be glad to discuss about it or even give some lessons. I\'m looking forward to meeting you soon ! Cheers ' %>
        <%= f.input :lesson, as: :boolean, placeholder: 'true or false', label: 'Would you like to give lessons?' %>
      <BR>
        <%= f.button :submit, value:"Join us", class: 'btn btn-primary btn-lg' %>
      <% end %>
      <BR>
      </div>
    </div>
  </div>
</div>

app/views/talents/create.html.erb
<%= render 'form' %>

app/views/talents/edit.html.erb
<% content_for(:title_tag) do %>
  Edit your talent
<% end %>

<div class="container">
  <div class="row">
    <div class="new_talent">
      <div class="col-md-6 col-md-offset-3">
        <h2 class= "text-center"> <%=  icon("pencil")  %> Edit your talent !</h2>

        <%= simple_form_for(@talent) do |f| %>
          <%= f.association :category, label: 'Select the category matching your passion', class: 'section' %>
          <%= f.input :talent_proposed, label:'What\'s your talent?', placeholder: 'Piano' %>
          <%= f.input :description, label: 'Introduce yourself and describe your passion to the community', placeholder: 'Hello, I have been playing piano for 15 years and would be pleased to discuss about it or even give some lessons. I\'m looking forward to meeting you soon...' %>
          <%= f.input :lesson, as: :boolean, placeholder: 'true or false', label: 'Would you like to give lessons?' %>
          <%= f.button :submit, value:"Edit talent", class: 'btn btn-primary btn-lg' %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/talents/index.html.erb
<% content_for(:title_tag) do %>
  Results talents
<% end %>


<div class="container search_bar">
  <form action="<%= talents_path %>" class="flex-form navbar-left" role="search">
          <input type="text" name="query" class="form-control right-margin" placeholder="Search another talent" value=<%= "#{@query}" %>>
          <select type="text" name="category_id" class="form-control right-margin" value=<%= "#{@category}" %> >
            <option value="">All talent categories</option>
            <% @categories.each do |category| %>
              <option value="<%= category.id %>" <%= category.id == @category&.id ? "selected" : "" %>><%= category.name %></option>
            <% end %>
          </select>
          <button type="submit" class="btn btn-primary btn">Let's go!</button>
  </form>
</div>

<div class="container">
  <div class="row">
    <% @talents.each do |talent| %>
      <div class="col-xs-12 col-sm-4 center">
        <div class="card text-center">
          <div class="card-header">
            <h3><%= talent.talent_proposed.capitalize %></h3>
            <p><%= talent.category.name.capitalize %> </p>
          </div>
          <div class="card-avatar-large">
            <%= cl_image_tag image_path_for(talent.user), width: 150, heigth:150, crop: :crop, gravity: :face, class: "avatar-large" %>
          </div>
          <div class="card-description text-center">
            <h4><%= icon("user-o") %> <%= talent.user.first_name %></h4>
            <h6><%= icon("map-marker") %> <%= talent.user.address %></h6>
          </div>
          <%= link_to "See more", talent_path(talent), class: "btn btn-primary see_more" %>
        </div>
      </div>
    <% end -%>
  </div>
</div>

app/views/talents/new.html.erb
<%= render 'form' %>

app/views/talents/show.html.erb
<% content_for(:title_tag) do %>
  Talent <%= @talent.talent_proposed.capitalize %>
<% end %>
<div class="container">
  <div class="row">
    <h3 class="text-center"><%= @talent.user.name %>'s talent</h3>
    <div class="col-xs-12 col-sm-6">
      <div class="m-profile material-shadow-1">
        <div class="card show_height">
          <div class="card-header text-center">
            <h3><%= @talent.talent_proposed.capitalize %></h3>
            <p><%= @talent.category.name.capitalize %> </p>
          </div>
          <br>
          <div class="user_info">
            <div class="card-avatar-large">
              <%= cl_image_tag image_path_for(@talent.user), width: 150, heigth:150, crop: :fill, class: "avatar-large" %>
            </div>
            <div class="card-description">
              <p id="name"> <%= @talent.user.name %></p>
              <p><%= icon("map-marker") %> <%= @talent.user.address %></p>
              <p><%= icon("book") %> Teach :  <%= @talent.lesson ? icon("check") : icon("times") %></p>
            </div>
          </div>
          <BR>
          <p class="talent-desciption"><%= icon("star") %> <%= @talent.description %></p>
          <% if @talent.user == current_user %>
            <p><%=  icon("pencil")  %> <%= link_to 'Edit', edit_talent_path(@talent) %>
          <% end %>
        </div>
      </div>
    </div>


    <div class="col-xs-12 col-sm-6">
      <div class="card show_height">
        <h3>Start the conversation</h3>
          <%= simple_form_for(:conversation, url: :conversations) do |f| %>
            <%= f.input :subject, label: 'Purpose of the discussion' %>
            <%= f.input :user_id, input_html: { value: @recipient.id }, as: :hidden %>
            <%= f.input :body, as: :text, label: 'Your message' %>
            <%= f.button :submit, value: "Contact #{@recipient.first_name}" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>