config/routes.rb
Rails.application.routes.draw do
mount Attachinary::Engine => "/attachinary"
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }

  resources :talents, only: [:create, :new, :update, :edit, :index, :show]
  resource :profile, only: :show


  resources :conversations do
    resources :messages
  end

  resources :conversations, only: [:show] do
    resources :appointments, only: :create
  end

  root to: 'pages#home'
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @conversations = current_user.mailbox.conversations
  end

  def show
    @conversation = current_user.mailbox.conversations.find(params[:id])
    @conversation.receipts.each do |receipt|
      receipt.mark_as_read if receipt.receiver == current_user
    end
    @receipts = @conversation.receipts_for(current_user).order(created_at: :asc)
    @appointment = Appointment.new
  end

  def new
    @recipients = User.all - [current_user]
  end

  def create
    recipient = User.find(params[:conversation][:user_id])
    receipt = current_user.send_message(recipient, params[:conversation][:body], params[:conversation][:subject])
    redirect_to conversation_path(receipt.conversation)
  end
end

app/views/conversations/index.html.erb
<% content_for(:title_tag) do %>
  Conversations
<% end %>

<% if @conversations.any? %>
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h3 class="text-center">All ongoing conversations with talents</h3>
        <div class="message">
          <% @conversations.each do |conversation| %>
            <div class="sender-avatar">
              <%= cl_image_tag image_path_for(destinator_for(conversation)), width: 75, heigth: 75, crop: :fill, class: "avatar" %>
              <div class="sender-conversation">
                <p><%= destinator_for(conversation).name %></p>
                <p><%= link_to conversation.subject, conversation_path(conversation) %></p>
              </div>
              <div class="unread-messages">
                <span class="badge"> <%= conversation.receipts_for(current_user).inbox.is_unread.count %></span>
              </div>
            </div>
          <% end %>
        </div>
        <BR>
     </div>
    </div>
  </div>
<% else %>
  <br/>
    <center><br/><h1>You have no conversation</h1><br/>
      <%= image_tag "message.jpg", size: "450x450" %>
<% end %>
<br>
<br>
  <div class=text-center>
    <%= link_to "Find another talent ! ", talents_path, class: 'btn btn-primary btn-lg' %>
  </div>

app/views/conversations/new.html.erb
<div class="container">
    <div class="row">
    <h1>New conversation </h1>
    <%= form_tag conversations_path, method: :post do %>
      <div><%= select_tag :user_id, options_from_collection_for_select(@recipients, :id, :name) %></div>
      <div><%= text_field_tag :subject, nil, placeholder: "subject" %></div>
      <div><%= text_area_tag :body, nil, placeholder: "Leave a comment" %></div>
      <%= submit_tag %>
    <% end %>
  </div>
</div>

app/views/conversations/show.html.erb
<div class="container">
  <div class="row center">
    <h1 class="text-center titre-discussion"> <%= @conversation.subject %></h1>
    <div class="col-xs-12 col-sm-8 col-md-offset-2">
      <div class="conversations">
      <% @receipts.each do |receipt| %>
        <div class="sent-msg">
          <% if receipt.message.sender != current_user %>
            <div class="sent-msg-sender">
              <h3><%= cl_image_tag image_path_for(receipt.message.sender), width: 35, heigth: 35, crop: :fill, class: "avatar-small" %>
                  <%= receipt.message.sender.first_name %></h3>
              <div class="msg-body-sender"><h4><%= receipt.message.body %></h4></div>
            </div>
          <% else %>
            <div class="sent-msg-receiver">
              <h3><%= cl_image_tag image_path_for(receipt.message.sender), width: 35, heigth: 35, crop: :fill, class: "avatar-small" %>
                  <%= receipt.message.sender.first_name %></h3>
              <div class="msg-body-receiver"><h4><%= receipt.message.body %></h4></div>
            </div>
          <% end %>
        </div>
      <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-8 col-md-offset-2" id="new_message">
      <div class="new_conversation">
        <h3> New message: </h3>
        <%= form_tag conversation_messages_path(@conversation), method: :post do %>

          <%= text_area_tag :body %>
          <div class="new-message-form">
          <!-- Button trigger modal -->
            <div class="btn btn-primary btn-lg" id="meeting-button" data-toggle="modal" data-target="#myModalNorm">
                Meeting Scheduled !?
            </div>
            <%= submit_tag "Send", class: 'btn btn-primary btn-lg', id: 'send-button' %>
          </div>
        <% end %>
      </div>
    <BR>
        <!-- Modal -->
        <div class="modal fade" id="myModalNorm" tabindex="-1" role="dialog"
             aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title" id="myModalLabel">
                            Tell us about your meeting,
                            When and Where will it be ?
                        </h4>

        <link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" />

        <!-- Inline CSS based on choices in "Settings" tab -->
              <style>.bootstrap-iso .formden_header h2, .bootstrap-iso .formden_header p, .bootstrap-iso form{font-family: Arial, Helvetica, sans-serif; color: black}.bootstrap-iso form button, .bootstrap-iso form button:hover{color: white !important;} .asteriskField{color: red;}</style>

              <!-- HTML Form (wrapped in a .bootstrap-iso div) -->
              <div class="bootstrap-iso">
               <div class="container-fluid">
                <div class="row">
                 <div class="col-md-6 col-sm-6 col-xs-12">
                  <form method="post" action="<%= conversation_appointments_path(@conversation) %>">
                   <div class="form-group">
                   <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
                    <label class="control-label requiredField" for="date">
                     Date
                     <span class="asteriskField">
                      *
                     </span>
                    </label>
                    <div class="input-group">
                     <div class="input-group-addon">
                      <i class="fa fa-calendar">
                      </i>
                     </div>
                     <input class="form-control datepicker" id="date" name="appointment[date]" placeholder="dd/mm/yyyy" type="text"/>
                    </div>
                   </div>

                   <div class="form-group ">
                    <label class="control-label requiredField" for="text">
                     Address
                     <span class="asteriskField">
                      *
                     </span>
                    </label>
                    <div class="input-group">
                     <div class="input-group-addon">
                      <i class="fa fa-location-arrow">
                      </i>
                     </div>
                     <input class="form-control" id="text" name="appointment[location]" type="text"/>
                    </div>
                   </div>
                   <div class="form-group">
                    <div>
                     <button class="btn btn-primary" name="submit" type="submit">
                      Let's go !
                     </button>
                    </div>
                   </div>
                  </div>
                  </form>
                 </div>
                </div>
               </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>
</form>